### ISSUE TITLE
Missing Database

### ISSUE THREAD

**Issue by Spooonky** [mgtrrz/timeclock#1]
Hello, 
I know this is a very old project of yours, but could you possibly provide a template for the database?

**Comment by mgtrrz** [comment]
hey @Spooonky let me take a look and see if i can provide it

**Comment by mgtrrz** [comment]
Actually i just noticed that your fork has a SQL dump, did you end up scraping that from one of the sites? Either way, glad you got that working and sorry I got to your Issue a bit late

**Comment by mgtrrz** [comment]
Added the database_schema file: https://github.com/mgtrrz/timeclock/blob/master/database_schema.sql
Just realized that the sql file that's in your fork was in my commit history.

Anyway, let me know if you have any questions! Hope you're getting some good use out of the tool
